server:
  port: 8889
---
spring:
  profiles: local
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/user?autoReconnect=true&autoReconnectForPools=true&useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 200
      max-wait: 3000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      max-evictable-idle-time-millis: 400000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: -1
      filters: stat,wall
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
      aop-patterns: com.baiyan.service.*
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.png,*.jpg,*.css,*.ico,/druid/*'
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
        login-username: root
        login-password: 123456
        allow:
        deny:
    flyway:
      baseline-on-migrate: true
      enabled: true
      locations: classpath:/db/migration
      out-of-order: true

logging:
  level:
    com:
      baiyan: debug

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:mapper/*.xml

# login config
auth:
  login:
    config:
      captcha: false
      password: true
      tokenTimeout: 86400
  resourceApi: /api/**
  exclude: /api/**/api-docs

# swagger config
swagger:
  config:
    enable: true
    groupName: baiyan
    basePackage: com.baiyan.auth
    title: 柏炎鉴权中心
    description: 柏炎鉴权中心api
    version: 1.0.0-SNAPSHOT

# web serializable config
baiyan:
  config:
    jackson:
      enable: true
---
spring:
  profiles: prod
server:
  port: 8883